// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporSalonuYonetim_web.Models;

#nullable disable

namespace SporSalonuYonetim_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SporSalonuYonetim_web.Models.Antrenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UzmanlikAlanlari")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Antrenorler");
                });

            modelBuilder.Entity("SporSalonuYonetim_web.Models.AntrenorHizmet", b =>
                {
                    b.Property<int>("AntrenorId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("HizmetId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("AntrenorId", "HizmetId");

                    b.HasIndex("HizmetId");

                    b.ToTable("AntrenorHizmetleri");
                });

            modelBuilder.Entity("SporSalonuYonetim_web.Models.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("SporSalonuYonetim_web.Models.AntrenorHizmet", b =>
                {
                    b.HasOne("SporSalonuYonetim_web.Models.Antrenor", "Antrenor")
                        .WithMany("AntrenorHizmetleri")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SporSalonuYonetim_web.Models.Hizmet", "Hizmet")
                        .WithMany("AntrenorHizmetleri")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("SporSalonuYonetim_web.Models.Antrenor", b =>
                {
                    b.Navigation("AntrenorHizmetleri");
                });

            modelBuilder.Entity("SporSalonuYonetim_web.Models.Hizmet", b =>
                {
                    b.Navigation("AntrenorHizmetleri");
                });
#pragma warning restore 612, 618
        }
    }
}
